### ISSUE TITLE
Make MHQ to be deployable, just like in ARMA2

### ISSUE THREAD

**Issue by johnsmm** [Liveandletdie/becti_zerty_OFPS_guerrilla.Stratis#6]
MHQ needs to be deployable to build and must cost money. I would say 10,000.

**Comment by johnsmm** [comment]
see if you can use any of the code from arma 2 to make this work.

**Comment by SpanishSurfer** [comment]
No, waste of time. We have other more pressing matters and our bases
require military installation that costs $10k to start a base.
